# Generated by Django 4.2.4 on 2023-08-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictureVoterApp', '0002_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='drawing_name',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
