# Generated by Django 4.2.4 on 2023-08-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictureVoterApp', '0003_drawing_drawing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
