# Generated by Django 4.2.4 on 2023-08-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PictureVoterApp', '0004_drawing_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='username',
            field=models.CharField(default='None Assigned', max_length=50),
        ),
    ]
